/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as DescobertasRouteImport } from './routes/descobertas'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MissoesRouteImport } from './routes/missoes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedJornadaRouteImport } from './routes/_authenticated/jornada'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const DescobertasRoute = DescobertasRouteImport.update({
  id: '/descobertas',
  path: '/descobertas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesRoute = MissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJornadaRoute = AuthenticatedJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conquistas': typeof ConquistasRoute
  '/descobertas': typeof DescobertasRoute
  '/entrar': typeof EntrarRoute
  '/inteligencia': typeof InteligenciaRoute
  '/mapa': typeof MapaRoute
  '/missoes': typeof MissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conquistas': typeof ConquistasRoute
  '/descobertas': typeof DescobertasRoute
  '/entrar': typeof EntrarRoute
  '/inteligencia': typeof InteligenciaRoute
  '/mapa': typeof MapaRoute
  '/missoes': typeof MissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/conquistas': typeof ConquistasRoute
  '/descobertas': typeof DescobertasRoute
  '/entrar': typeof EntrarRoute
  '/inteligencia': typeof InteligenciaRoute
  '/mapa': typeof MapaRoute
  '/missoes': typeof MissoesRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/jornada': typeof AuthenticatedJornadaRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conquistas'
    | '/descobertas'
    | '/entrar'
    | '/inteligencia'
    | '/mapa'
    | '/missoes'
    | '/perfil'
    | '/ranking'
    | '/reset-password'
    | '/jornada'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conquistas'
    | '/descobertas'
    | '/entrar'
    | '/inteligencia'
    | '/mapa'
    | '/missoes'
    | '/perfil'
    | '/ranking'
    | '/reset-password'
    | '/jornada'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/conquistas'
    | '/descobertas'
    | '/entrar'
    | '/inteligencia'
    | '/mapa'
    | '/missoes'
    | '/perfil'
    | '/ranking'
    | '/reset-password'
    | '/_authenticated/jornada'
    | '/_authenticated/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ConquistasRoute: typeof ConquistasRoute
  DescobertasRoute: typeof DescobertasRoute
  EntrarRoute: typeof EntrarRoute
  InteligenciaRoute: typeof InteligenciaRoute
  MapaRoute: typeof MapaRoute
  MissoesRoute: typeof MissoesRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descobertas': {
      id: '/descobertas'
      path: '/descobertas'
      fullPath: '/descobertas'
      preLoaderRoute: typeof DescobertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes': {
      id: '/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof MissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jornada': {
      id: '/_authenticated/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof AuthenticatedJornadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedJornadaRoute: typeof AuthenticatedJornadaRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedJornadaRoute: AuthenticatedJornadaRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ConquistasRoute: ConquistasRoute,
  DescobertasRoute: DescobertasRoute,
  EntrarRoute: EntrarRoute,
  InteligenciaRoute: InteligenciaRoute,
  MapaRoute: MapaRoute,
  MissoesRoute: MissoesRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
